// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NineAPI.Data;

#nullable disable

namespace NineAPI.Migrations
{
    [DbContext(typeof(NineAPIContext))]
    [Migration("20250811153415_book data added")]
    partial class bookdataadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NineAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "George Orwell",
                            Title = "1984",
                            YearPublished = 1949
                        },
                        new
                        {
                            Id = 2,
                            Author = "Bill  Smith",
                            Title = "To Kill a Mockingbird",
                            YearPublished = 1960
                        },
                        new
                        {
                            Id = 3,
                            Author = "F. Scott Fitzgerald",
                            Title = "The Great Gatsby",
                            YearPublished = 1925
                        },
                        new
                        {
                            Id = 4,
                            Author = "Aldous Huxley",
                            Title = "Brave New World",
                            YearPublished = 1932
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
